// <auto-generated />
using System;
using DOANLAPTRINHWWEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DOANLAPTRINHWWEB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617064837_AddUserFavoriteStory")]
    partial class AddUserFavoriteStory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterNumber = 1,
                            Content = "Tại gia tộc Tiêu thị của Đế quốc Đấu Khí, một thiếu niên khoảng mười bảy mười tám tuổi đang ngồi thẫn thờ trên một tảng đá lớn bên bờ suối.<br><br>Thiếu niên này dung mạo tuấn tú, nhưng lúc này trên mặt lại đầy vẻ u sầu. Hắn tên là Tiêu Viêm, là con trai trưởng của Tiêu gia, nhưng lại bị người trong gia tộc khinh thường vì không thể luyện đan.<br><br>\"Ta lại là phế vật sao...\" Tiêu Viêm tự cười tự nói, trong lòng tràn ngập bất lực.",
                            CreatedAt = new DateTime(2026, 5, 18, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(4262),
                            StoryId = 1,
                            Title = "Thiên tài luyện dược"
                        },
                        new
                        {
                            Id = 2,
                            ChapterNumber = 2,
                            Content = "Đêm đó, khi Tiêu Viêm đang ngủ say, một luồng ánh sáng kỳ lạ đột nhiên xuất hiện trong phòng hắn. Một lão nhân với mái tóc bạc phơ bước ra từ trong ánh sáng.<br><br>\"Tiểu tử, ngươi có muốn thay đổi số phận của mình không?\" Lão nhân nhìn Tiêu Viêm, trong mắt chứa đựng một vẻ thâm sâu khó lường.<br><br>Tiêu Viêm giật mình tỉnh giấc, nhìn lão nhân trước mặt, trong lòng tràn ngập kinh ngạc.",
                            CreatedAt = new DateTime(2026, 5, 19, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(4442),
                            StoryId = 1,
                            Title = "Lão nhân bí ẩn"
                        },
                        new
                        {
                            Id = 3,
                            ChapterNumber = 1,
                            Content = "Tại một vùng núi non hùng vĩ, một thiếu niên khoảng mười lăm mười sáu tuổi đang ngồi dưới gốc cây cổ thụ, nhắm mắt dưỡng thần.<br><br>Thiếu niên này tên là Lâm Động, là con trai của Lâm gia - một trong tứ đại gia tộc của Thiên Đan thành. Dù còn trẻ, nhưng hắn đã có tu vi đạt đến Đan Nguyên cảnh.<br><br>\"Đại tỷ, đệ nhất định sẽ không làm thất vọng mong đợi của người.\" Lâm Động mở mắt, trong mắt chứa đựng sự kiên định.",
                            CreatedAt = new DateTime(2026, 5, 23, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(4445),
                            StoryId = 2,
                            Title = "Lâm Động"
                        },
                        new
                        {
                            Id = 4,
                            ChapterNumber = 2,
                            Content = "Ba ngày sau, Lâm gia tổ chức một buổi thử thách cho các thiếu niên trong gia tộc. Đây là cơ hội để Lâm Động chứng minh thực lực của mình.<br><br>Trên võ đài, Lâm Động đối mặt với đối thủ mạnh nhất của mình - Lâm Lăng. Hai người nhìn nhau, không khí xung quanh trở nên căng thẳng.<br><br>\"Đến đi, để ta xem thực lực của ngươi đến đâu!\" Lâm Lăng gầm lên, toàn thân tỏa ra khí thế mạnh mẽ.",
                            CreatedAt = new DateTime(2026, 5, 24, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(4447),
                            StoryId = 2,
                            Title = "Thử thách"
                        },
                        new
                        {
                            Id = 5,
                            ChapterNumber = 1,
                            Content = "Đại thiên thế giới, một nơi rộng lớn vô biên, nơi vạn tộc cùng tồn tại. Ở đây, cường giả tôn trọng, kẻ yếu bị chà đạp.<br><br>Tại một góc của đại thiên thế giới, một thiếu niên tên là Lâm Động đang đứng trên đỉnh núi, nhìn xuống thế giới rộng lớn phía dưới.<br><br>\"Ta nhất định sẽ đứng trên đỉnh cao của thế giới này!\" Lâm Động gầm lên, trong mắt chứa đựng sự kiên định không thể lay chuyển.",
                            CreatedAt = new DateTime(2026, 5, 28, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(4449),
                            StoryId = 3,
                            Title = "Đại thiên thế giới"
                        },
                        new
                        {
                            Id = 6,
                            ChapterNumber = 1,
                            Content = "Kudo Shinichi, một thám tử trung học nổi tiếng, bị tổ chức áo đen tấn công và ép uống thuốc độc. Thuốc khiến cơ thể hắn teo nhỏ thành một đứa trẻ 7 tuổi.<br><br>Shinichi đổi tên thành Edogawa Conan và sống cùng gia đình Mori. Hắn quyết tâm tìm ra tổ chức áo đen và lấy lại hình dáng cũ.<br><br>\"Dù cơ thể có teo nhỏ, trí tuệ thám tử vẫn không thay đổi!\"",
                            CreatedAt = new DateTime(2026, 4, 18, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(4451),
                            StoryId = 6,
                            Title = "Thám tử lừng danh变小"
                        },
                        new
                        {
                            Id = 7,
                            ChapterNumber = 2,
                            Content = "Tại một nhà hàng sang trọng, một vụ án mạng xảy ra. Nạn nhân là một doanh nhân giàu có bị phát hiện đã chết trong phòng riêng.<br><br>Conan cùng nhóm thám tử nhí bắt đầu điều tra. Bằng những manh mối tinh tế, Conan dần dần hé lộ chân tướng của kẻ sát nhân.<br><br>\"Sự thật chỉ có một!\"",
                            CreatedAt = new DateTime(2026, 4, 19, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(4453),
                            StoryId = 6,
                            Title = "Vụ án nhà hàng"
                        },
                        new
                        {
                            Id = 8,
                            ChapterNumber = 1,
                            Content = "Nobi Nobita, một cậu học sinh yếu đuối và hay bị bắt nạt, luôn ước mơ có một người bạn giúp đỡ mình.<br><br>Một ngày, từ ngăn kéo của Nobita, một chú mèo máy màu xanh xuất hiện. Đó là Doraemon, đến từ thế kỷ 22 để giúp Nobita.<br><br>\"Tao sẽ giúp mày thay đổi số phận!\"",
                            CreatedAt = new DateTime(2026, 3, 19, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(4455),
                            StoryId = 7,
                            Title = "Doraemon xuất hiện"
                        },
                        new
                        {
                            Id = 9,
                            ChapterNumber = 2,
                            Content = "Doraemon lấy ra bảo bối Cánh cửa thần kỳ, có thể đi đến bất cứ đâu chỉ cần nghĩ về nơi đó.<br><br>Nobita cùng Doraemon và bạn bè đi đến nhiều nơi thú vị: rừng rậm, sa mạc, thậm chí là vương quốc của khủng long.<br><br>\"Cuộc phiêu lưu mới bắt đầu!\"",
                            CreatedAt = new DateTime(2026, 3, 20, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(4457),
                            StoryId = 7,
                            Title = "Bảo bối Cánh cửa thần kỳ"
                        },
                        new
                        {
                            Id = 10,
                            ChapterNumber = 1,
                            Content = "Trong làng Foosha, cậu bé Monkey D. Luffy luôn mơ ước trở thành Vua Hải Tặc. Hắn ăn trái ác quỷ Gomu Gomu no, biến cơ thể thành cao su.<br><br>Luffy quyết tâm ra khơi, tìm kiếm băng hải tặc và kho báu One Piece huyền thoại.<br><br>\"Ta sẽ trở thành Vua Hải Tặc!\"",
                            CreatedAt = new DateTime(2026, 2, 17, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(4459),
                            StoryId = 8,
                            Title = "Sự khởi đầu của huyền thoại"
                        },
                        new
                        {
                            Id = 11,
                            ChapterNumber = 2,
                            Content = "Luffy đến làng Shimotsuki và gặp Roronoa Zoro, một kiếm sĩ nổi tiếng với kỹ năng ba kiếm.<br><br>Sau khi chứng kiến sức mạnh và lòng dũng cảm của Zoro, Luffy mời hắn gia nhập băng Mũ Rơm.<br><br>\"Hãy trở thành kiếm sĩ mạnh nhất của băng ta!\"",
                            CreatedAt = new DateTime(2026, 2, 18, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(4461),
                            StoryId = 8,
                            Title = "Zoro gia nhập băng"
                        });
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("StoryId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tiên Hiệp",
                            Slug = "tien-hiep"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Huyền Huyễn",
                            Slug = "huyen-huyen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kiếm Hiệp",
                            Slug = "kiem-hiep"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Đô Thị",
                            Slug = "do-thi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mạt Thế",
                            Slug = "mat-the"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ngôn Tình",
                            Slug = "ngon-tinh"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hệ Thống",
                            Slug = "he-thong"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Lịch Sử",
                            Slug = "lich-su"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Trinh Thám",
                            Slug = "trinh-tham"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hoạt Hình",
                            Slug = "hoat-hinh"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Hành Động",
                            Slug = "hanh-dong"
                        });
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Score = 5,
                            StoryId = 1,
                            UserName = ""
                        },
                        new
                        {
                            Id = 2,
                            Score = 4,
                            StoryId = 1,
                            UserName = ""
                        },
                        new
                        {
                            Id = 3,
                            Score = 5,
                            StoryId = 2,
                            UserName = ""
                        },
                        new
                        {
                            Id = 4,
                            Score = 4,
                            StoryId = 3,
                            UserName = ""
                        },
                        new
                        {
                            Id = 5,
                            Score = 5,
                            StoryId = 3,
                            UserName = ""
                        },
                        new
                        {
                            Id = 6,
                            Score = 5,
                            StoryId = 6,
                            UserName = ""
                        },
                        new
                        {
                            Id = 7,
                            Score = 5,
                            StoryId = 6,
                            UserName = ""
                        },
                        new
                        {
                            Id = 8,
                            Score = 5,
                            StoryId = 7,
                            UserName = ""
                        },
                        new
                        {
                            Id = 9,
                            Score = 4,
                            StoryId = 7,
                            UserName = ""
                        },
                        new
                        {
                            Id = 10,
                            Score = 5,
                            StoryId = 8,
                            UserName = ""
                        },
                        new
                        {
                            Id = 11,
                            Score = 5,
                            StoryId = 8,
                            UserName = ""
                        });
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.ReadingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ReadingHistories");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Thiên Tằm Thổ Đậu",
                            CoverImage = "https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/Fight_Break_Sphere_drama_poster.jpeg/250px-Fight_Break_Sphere_drama_poster.jpeg",
                            CreatedAt = new DateTime(2026, 5, 18, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1118),
                            Description = "Thiên Tằm Thổ Đậu - một thiên tài luyện dược, vì không thể luyện đan mà bị người nhà khinh thường. Một ngày nọ, hắn gặp được một lão nhân bí ẩn, từ đó bước vào con đường tu tiên đầy huyền thoại.",
                            Status = "Hoàn thành",
                            Title = "Đấu Phá Thương Khung",
                            UpdatedAt = new DateTime(2026, 6, 12, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1322),
                            ViewCount = 15420
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Mạc Mặc",
                            CoverImage = "https://static.wikia.nocookie.net/martial-peak-mp/images/1/17/Yang_Kai.png/revision/latest?cb=20180221130629",
                            CreatedAt = new DateTime(2026, 5, 23, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1494),
                            Description = "Câu chuyện về một thiếu niên tên là Lâm Động, trên vai gánh vác trọng trách gia tộc, bước vào thế giới rộng lớn của võ lâm, dùng mười năm thời gian để viết nên một truyền thuyết.",
                            Status = "Hoàn thành",
                            Title = "Vũ Luyện Đỉnh Phong",
                            UpdatedAt = new DateTime(2026, 6, 14, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1495),
                            ViewCount = 12350
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Thiên Tằm Thổ Đậu",
                            CoverImage = "/images/default-cover.jpg",
                            CreatedAt = new DateTime(2026, 5, 28, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1499),
                            Description = "Đại thiên thế giới, vạn tộc lâm lập, hùng giả như rừng, cường giả như mây. Một thiếu niên từ đại tộc bước ra, dùng đôi tay của mình, chém phá hết thảy chướng ngại, đứng trên đỉnh cao của thiên hạ.",
                            Status = "Hoàn thành",
                            Title = "Nguyên Tôn",
                            UpdatedAt = new DateTime(2026, 6, 16, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1499),
                            ViewCount = 18200
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Vong Ngữ",
                            CoverImage = "/images/default-cover.jpg",
                            CreatedAt = new DateTime(2026, 6, 2, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1502),
                            Description = "Một thiếu niên bình thường, vì cơ duyên xảo hợp mà bước vào thế giới tu tiên. Từ một phàm nhân nhỏ bé, dần dần trưởng thành, cuối cùng trở thành một đại năng giả đứng đầu thiên hạ.",
                            Status = "Đang ra",
                            Title = "Phàm Nhân Tu Tiên",
                            UpdatedAt = new DateTime(2026, 6, 17, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1503),
                            ViewCount = 9870
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Cô Đơn Địa Phi",
                            CoverImage = "/images/default-cover.jpg",
                            CreatedAt = new DateTime(2026, 6, 7, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1506),
                            Description = "Trong một thế giới nơi cường giả tôn trọng, một thiếu niên với thiên tài luyện dược độc nhất vô nhị, dùng đan dược để thay đổi số phận của mình.",
                            Status = "Đang ra",
                            Title = "Thần Đạo Đan Tôn",
                            UpdatedAt = new DateTime(2026, 6, 17, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1507),
                            ViewCount = 7650
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            AuthorName = "Aoyama Gōshō",
                            CoverImage = "/img/Conan.jpg",
                            CreatedAt = new DateTime(2026, 4, 18, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1509),
                            Description = "Edogawa Conan, một thám tử tiểu học với trí tuệ phi thường, cùng nhóm thám tử nhí giải quyết các vụ án khó khăn. Truyện xoay quanh cuộc chiến chống lại tổ chức áo đen.",
                            Status = "Đang ra",
                            Title = "Thám Tử Lừng Danh Conan",
                            UpdatedAt = new DateTime(2026, 6, 17, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1510),
                            ViewCount = 25000
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            AuthorName = "Fujiko F. Fujio",
                            CoverImage = "https://books.google.com/books/content?id=UuoArgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
                            CreatedAt = new DateTime(2026, 3, 19, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1685),
                            Description = "Doraemon - chú mèo máy đến từ thế kỷ 22, cùng với Nobita và những người bạn trải qua những cuộc phiêu lưu kỳ thú nhờ vào các bảo bối thần kỳ.",
                            Status = "Hoàn thành",
                            Title = "Doraemon",
                            UpdatedAt = new DateTime(2026, 5, 18, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1686),
                            ViewCount = 32000
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            AuthorName = "Eiichiro Oda",
                            CoverImage = "/img/once pice.jpg",
                            CreatedAt = new DateTime(2026, 2, 17, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1690),
                            Description = "Luffy cùng băng Mũ Rơm bắt đầu hành trình tìm kiếm kho báu huyền thoại One Piece và trở thành Vua Hải Tặc. Truyện kể về tình bạn, ước mơ và những cuộc chiến đầy kịch tính.",
                            Status = "Đang ra",
                            Title = "One Piece",
                            UpdatedAt = new DateTime(2026, 6, 17, 13, 48, 37, 40, DateTimeKind.Local).AddTicks(1690),
                            ViewCount = 45000
                        });
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.StoryGenre", b =>
                {
                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("StoryId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("StoryGenre");

                    b.HasData(
                        new
                        {
                            StoryId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            StoryId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            StoryId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            StoryId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            StoryId = 5,
                            GenreId = 7
                        },
                        new
                        {
                            StoryId = 6,
                            GenreId = 9
                        },
                        new
                        {
                            StoryId = 7,
                            GenreId = 10
                        },
                        new
                        {
                            StoryId = 8,
                            GenreId = 11
                        });
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 18, 13, 48, 37, 39, DateTimeKind.Local).AddTicks(7012),
                            Email = "admin@doctruyen.com",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 28, 13, 48, 37, 39, DateTimeKind.Local).AddTicks(7339),
                            Email = "user@doctruyen.com",
                            PasswordHash = "BPiZbadjt6lpsQKO4wB1aerzpjVIbdqyEdUSyFud+Ps=",
                            Role = "User",
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.UserFavoriteStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId", "StoryId")
                        .IsUnique();

                    b.ToTable("UserFavoriteStories");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.UserStoryFollow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId", "StoryId")
                        .IsUnique();

                    b.ToTable("UserStoryFollows");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Chapter", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.Story", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Comment", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.Chapter", "Chapter")
                        .WithMany("Comments")
                        .HasForeignKey("ChapterId");

                    b.HasOne("DOANLAPTRINHWWEB.Models.Story", "Story")
                        .WithMany("Comments")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Rating", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.Story", "Story")
                        .WithMany("Ratings")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.ReadingHistory", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DOANLAPTRINHWWEB.Models.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DOANLAPTRINHWWEB.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Story", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.User", "Author")
                        .WithMany("Stories")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.StoryGenre", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.Genre", "Genre")
                        .WithMany("StoryGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOANLAPTRINHWWEB.Models.Story", "Story")
                        .WithMany("StoryGenres")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.UserFavoriteStory", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.Story", "Story")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOANLAPTRINHWWEB.Models.User", "User")
                        .WithMany("FavoriteStories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.UserStoryFollow", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.Story", "Story")
                        .WithMany("Followers")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOANLAPTRINHWWEB.Models.User", "User")
                        .WithMany("FollowedStories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Chapter", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Genre", b =>
                {
                    b.Navigation("StoryGenres");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Story", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Comments");

                    b.Navigation("FavoritedBy");

                    b.Navigation("Followers");

                    b.Navigation("Ratings");

                    b.Navigation("StoryGenres");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.User", b =>
                {
                    b.Navigation("FavoriteStories");

                    b.Navigation("FollowedStories");

                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
