// <auto-generated />
using System;
using DOANLAPTRINHWWEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DOANLAPTRINHWWEB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530143415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterNumber = 1,
                            Content = "Tại gia tộc Tiêu thị của Đế quốc Đấu Khí, một thiếu niên khoảng mười bảy mười tám tuổi đang ngồi thẫn thờ trên một tảng đá lớn bên bờ suối.<br><br>Thiếu niên này dung mạo tuấn tú, nhưng lúc này trên mặt lại đầy vẻ u sầu. Hắn tên là Tiêu Viêm, là con trai trưởng của Tiêu gia, nhưng lại bị người trong gia tộc khinh thường vì không thể luyện đan.<br><br>\"Ta lại là phế vật sao...\" Tiêu Viêm tự cười tự nói, trong lòng tràn ngập bất lực.",
                            CreatedAt = new DateTime(2026, 4, 30, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(9402),
                            StoryId = 1,
                            Title = "Thiên tài luyện dược"
                        },
                        new
                        {
                            Id = 2,
                            ChapterNumber = 2,
                            Content = "Đêm đó, khi Tiêu Viêm đang ngủ say, một luồng ánh sáng kỳ lạ đột nhiên xuất hiện trong phòng hắn. Một lão nhân với mái tóc bạc phơ bước ra từ trong ánh sáng.<br><br>\"Tiểu tử, ngươi có muốn thay đổi số phận của mình không?\" Lão nhân nhìn Tiêu Viêm, trong mắt chứa đựng một vẻ thâm sâu khó lường.<br><br>Tiêu Viêm giật mình tỉnh giấc, nhìn lão nhân trước mặt, trong lòng tràn ngập kinh ngạc.",
                            CreatedAt = new DateTime(2026, 5, 1, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(9520),
                            StoryId = 1,
                            Title = "Lão nhân bí ẩn"
                        },
                        new
                        {
                            Id = 3,
                            ChapterNumber = 1,
                            Content = "Tại một vùng núi non hùng vĩ, một thiếu niên khoảng mười lăm mười sáu tuổi đang ngồi dưới gốc cây cổ thụ, nhắm mắt dưỡng thần.<br><br>Thiếu niên này tên là Lâm Động, là con trai của Lâm gia - một trong tứ đại gia tộc của Thiên Đan thành. Dù còn trẻ, nhưng hắn đã có tu vi đạt đến Đan Nguyên cảnh.<br><br>\"Đại tỷ, đệ nhất định sẽ không làm thất vọng mong đợi của người.\" Lâm Động mở mắt, trong mắt chứa đựng sự kiên định.",
                            CreatedAt = new DateTime(2026, 5, 5, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(9522),
                            StoryId = 2,
                            Title = "Lâm Động"
                        },
                        new
                        {
                            Id = 4,
                            ChapterNumber = 2,
                            Content = "Ba ngày sau, Lâm gia tổ chức một buổi thử thách cho các thiếu niên trong gia tộc. Đây là cơ hội để Lâm Động chứng minh thực lực của mình.<br><br>Trên võ đài, Lâm Động đối mặt với đối thủ mạnh nhất của mình - Lâm Lăng. Hai người nhìn nhau, không khí xung quanh trở nên căng thẳng.<br><br>\"Đến đi, để ta xem thực lực của ngươi đến đâu!\" Lâm Lăng gầm lên, toàn thân tỏa ra khí thế mạnh mẽ.",
                            CreatedAt = new DateTime(2026, 5, 6, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(9524),
                            StoryId = 2,
                            Title = "Thử thách"
                        },
                        new
                        {
                            Id = 5,
                            ChapterNumber = 1,
                            Content = "Đại thiên thế giới, một nơi rộng lớn vô biên, nơi vạn tộc cùng tồn tại. Ở đây, cường giả tôn trọng, kẻ yếu bị chà đạp.<br><br>Tại một góc của đại thiên thế giới, một thiếu niên tên là Lâm Động đang đứng trên đỉnh núi, nhìn xuống thế giới rộng lớn phía dưới.<br><br>\"Ta nhất định sẽ đứng trên đỉnh cao của thế giới này!\" Lâm Động gầm lên, trong mắt chứa đựng sự kiên định không thể lay chuyển.",
                            CreatedAt = new DateTime(2026, 5, 10, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(9525),
                            StoryId = 3,
                            Title = "Đại thiên thế giới"
                        });
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("StoryId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tiên Hiệp",
                            Slug = "tien-hiep"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Huyền Huyễn",
                            Slug = "huyen-huyen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kiếm Hiệp",
                            Slug = "kiem-hiep"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Đô Thị",
                            Slug = "do-thi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mạt Thế",
                            Slug = "mat-the"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ngôn Tình",
                            Slug = "ngon-tinh"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hệ Thống",
                            Slug = "he-thong"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Lịch Sử",
                            Slug = "lich-su"
                        });
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Score = 5,
                            StoryId = 1,
                            UserName = ""
                        },
                        new
                        {
                            Id = 2,
                            Score = 4,
                            StoryId = 1,
                            UserName = ""
                        },
                        new
                        {
                            Id = 3,
                            Score = 5,
                            StoryId = 2,
                            UserName = ""
                        },
                        new
                        {
                            Id = 4,
                            Score = 4,
                            StoryId = 3,
                            UserName = ""
                        },
                        new
                        {
                            Id = 5,
                            Score = 5,
                            StoryId = 3,
                            UserName = ""
                        });
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Thiên Tằm Thổ Đậu",
                            CoverImage = "/images/default-cover.jpg",
                            CreatedAt = new DateTime(2026, 4, 30, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(7364),
                            Description = "Thiên Tằm Thổ Đậu - một thiên tài luyện dược, vì không thể luyện đan mà bị người nhà khinh thường. Một ngày nọ, hắn gặp được một lão nhân bí ẩn, từ đó bước vào con đường tu tiên đầy huyền thoại.",
                            Status = "Hoàn thành",
                            Title = "Đấu Phá Thương Khung",
                            UpdatedAt = new DateTime(2026, 5, 25, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(7554),
                            ViewCount = 15420
                        },
                        new
                        {
                            Id = 2,
                            Author = "Mạc Mặc",
                            CoverImage = "/images/default-cover.jpg",
                            CreatedAt = new DateTime(2026, 5, 5, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(7669),
                            Description = "Câu chuyện về một thiếu niên tên là Lâm Động, trên vai gánh vác trọng trách gia tộc, bước vào thế giới rộng lớn của võ lâm, dùng mười năm thời gian để viết nên một truyền thuyết.",
                            Status = "Hoàn thành",
                            Title = "Vũ Luyện Đỉnh Phong",
                            UpdatedAt = new DateTime(2026, 5, 27, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(7670),
                            ViewCount = 12350
                        },
                        new
                        {
                            Id = 3,
                            Author = "Thiên Tằm Thổ Đậu",
                            CoverImage = "/images/default-cover.jpg",
                            CreatedAt = new DateTime(2026, 5, 10, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(7672),
                            Description = "Đại thiên thế giới, vạn tộc lâm lập, hùng giả như rừng, cường giả như mây. Một thiếu niên từ đại tộc bước ra, dùng đôi tay của mình, chém phá hết thảy chướng ngại, đứng trên đỉnh cao của thiên hạ.",
                            Status = "Hoàn thành",
                            Title = "Nguyên Tôn",
                            UpdatedAt = new DateTime(2026, 5, 29, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(7673),
                            ViewCount = 18200
                        },
                        new
                        {
                            Id = 4,
                            Author = "Vong Ngữ",
                            CoverImage = "/images/default-cover.jpg",
                            CreatedAt = new DateTime(2026, 5, 15, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(7675),
                            Description = "Một thiếu niên bình thường, vì cơ duyên xảo hợp mà bước vào thế giới tu tiên. Từ một phàm nhân nhỏ bé, dần dần trưởng thành, cuối cùng trở thành một đại năng giả đứng đầu thiên hạ.",
                            Status = "Đang ra",
                            Title = "Phàm Nhân Tu Tiên",
                            UpdatedAt = new DateTime(2026, 5, 30, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(7675),
                            ViewCount = 9870
                        },
                        new
                        {
                            Id = 5,
                            Author = "Cô Đơn Địa Phi",
                            CoverImage = "/images/default-cover.jpg",
                            CreatedAt = new DateTime(2026, 5, 20, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(7677),
                            Description = "Trong một thế giới nơi cường giả tôn trọng, một thiếu niên với thiên tài luyện dược độc nhất vô nhị, dùng đan dược để thay đổi số phận của mình.",
                            Status = "Đang ra",
                            Title = "Thần Đạo Đan Tôn",
                            UpdatedAt = new DateTime(2026, 5, 30, 21, 34, 13, 715, DateTimeKind.Local).AddTicks(7678),
                            ViewCount = 7650
                        });
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.StoryGenre", b =>
                {
                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("StoryId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("StoryGenre");

                    b.HasData(
                        new
                        {
                            StoryId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            StoryId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            StoryId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            StoryId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            StoryId = 5,
                            GenreId = 7
                        });
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Chapter", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.Story", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Comment", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.Chapter", "Chapter")
                        .WithMany("Comments")
                        .HasForeignKey("ChapterId");

                    b.HasOne("DOANLAPTRINHWWEB.Models.Story", "Story")
                        .WithMany("Comments")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Rating", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.Story", "Story")
                        .WithMany("Ratings")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.StoryGenre", b =>
                {
                    b.HasOne("DOANLAPTRINHWWEB.Models.Genre", "Genre")
                        .WithMany("StoryGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOANLAPTRINHWWEB.Models.Story", "Story")
                        .WithMany("StoryGenres")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Chapter", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Genre", b =>
                {
                    b.Navigation("StoryGenres");
                });

            modelBuilder.Entity("DOANLAPTRINHWWEB.Models.Story", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Comments");

                    b.Navigation("Ratings");

                    b.Navigation("StoryGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
